### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by Thomas7191** [aabssmc/SkHttp#1]
This is what happens when I create an HTTP server using skHttp, and if I frequently refresh the page in the browser by pressing F5, this error appears in the console.

[21:37:26 WARN]: [Skript] Plugin Skript v2.9.1-nightly-54f15c9 generated an exception while executing task 572334
java.lang.RuntimeException: java.io.IOException: Broken pipe
	at SkHttp.jar/lol.aabss.skhttp.objects.server.HttpExchange.respond(HttpExchange.java:59) ~[SkHttp.jar:?]
	at SkHttp.jar/lol.aabss.skhttp.elements.server.effects.EffExchangeRespond.execute(EffExchangeRespond.java:64) ~[SkHttp.jar:?]
	at Skript.jar/ch.njol.skript.util.AsyncEffect.lambda$walk$1(AsyncEffect.java:60) ~[Skript.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:62) ~[?:?]
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:137) ~[?:?]
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:102) ~[?:?]
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:58) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:542) ~[?:?]
	at jdk.httpserver@21.0.3/sun.net.httpserver.Request$WriteStream.write(Request.java:390) ~[jdk.httpserver:?]
	at jdk.httpserver@21.0.3/sun.net.httpserver.FixedLengthOutputStream.write(FixedLengthOutputStream.java:81) ~[jdk.httpserver:?]
	at java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:110) ~[?:?]
	at jdk.httpserver@21.0.3/sun.net.httpserver.PlaceholderOutputStream.write(ExchangeImpl.java:462) ~[jdk.httpserver:?]
	at SkHttp.jar/lol.aabss.skhttp.objects.server.HttpExchange.respond(HttpExchange.java:55) ~[SkHttp.jar:?]
	... 8 more

and this:

[21:38:37 WARN]: [Skript] Plugin Skript v2.9.1-nightly-54f15c9 generated an exception while executing task 572982
java.lang.RuntimeException: java.io.IOException: headers already sent
	at SkHttp.jar/lol.aabss.skhttp.objects.server.HttpExchange.respond(HttpExchange.java:59) ~[SkHttp.jar:?]
	at SkHttp.jar/lol.aabss.skhttp.elements.server.effects.EffExchangeRespond.execute(EffExchangeRespond.java:64) ~[SkHttp.jar:?]
	at Skript.jar/ch.njol.skript.util.AsyncEffect.lambda$walk$1(AsyncEffect.java:60) ~[Skript.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.io.IOException: headers already sent
	at jdk.httpserver@21.0.3/sun.net.httpserver.ExchangeImpl.sendResponseHeaders(ExchangeImpl.java:206) ~[jdk.httpserver:?]
	at jdk.httpserver@21.0.3/sun.net.httpserver.HttpExchangeImpl.sendResponseHeaders(HttpExchangeImpl.java:85) ~[jdk.httpserver:?]
	at SkHttp.jar/lol.aabss.skhttp.objects.server.HttpExchange.respond(HttpExchange.java:53) ~[SkHttp.jar:?]
	... 8 more

**Comment by Fusezion** [comment]
I'm gonna be fully honest, I cannot even read this, I'll keep an eye out for this but the main part of it seems to be "headers already sent" which I would assume means it sent the request once already
